### ISSUE TITLE
Implement DynamicTaskCallNode and StaticTaskCallNode

### ISSUE THREAD

**Issue by ydmeta** [ydzvulon/tasker#16]
on base of #14 

StaticTaskCallNode  form looks like:
```yaml
cmds:
- task: my-task
  vars: {f1: 3}
```

DynamicSelfTaskCallNode  form looks like:
```yaml
cmds:
- task my-task f1=3
```

DynamicOtherTaskCallNode  form looks like:
```yaml
cmds:
- task -d subdir my-task f1=3
```

make sure it works with includes
